version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - certs:/etc/nginx/dhparam
    environment:
      - DEFAULT_HOST=localhost
  dockergen:
    image: jwilder/docker-gen
    container_name: docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  server:
    image: python:3.7
    volumes:
      - ./server.py:/app/server.py
    entrypoint: python /app/server.py
    environment:
      - VIRTUAL_HOST=server1.jordanliu.net,server2.jordanliu.net
      - VIRTUAL_PORTS=8000,8001
    expose:
      - 8000
      - 8001
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - html:/usr/share/nginx/html
volumes:
  certs:
  vhost:
  html:




